import type { Question } from "./questions";
import { ENGLISH_B2_SUBJECT } from "./englishQuestions";

export const CAMBRIDGE_B2_FIRST = "Cambridge B2 First" as const;
export const CAMBRIDGE_B2_FIRST_SOURCE_URL = "https://www.cambridgeenglish.org/exams-and-tests/qualifications/first/format/";
const CAMBRIDGE_SOURCE = "Cambridge B2 First 題型架構參考；本站原創仿真題";

type CambridgeSeed = Omit<Question, "id" | "level" | "subject" | "source" | "sourceUrl" | "examFamily"> & {
  component: "Reading & Use of English" | "Listening";
  part: `Part ${1 | 2 | 3 | 4 | 5 | 6 | 7}`;
  questionType: string;
  stimulus?: string;
  audioScript?: string;
};

function makeQuestions(prefix: string, seeds: CambridgeSeed[]): Question[] {
  return seeds.map((seed, index) => ({
    ...seed,
    id: `CB2F-${prefix}-${String(index + 1).padStart(3, "0")}`,
    level: "中級",
    subject: ENGLISH_B2_SUBJECT,
    source: CAMBRIDGE_SOURCE,
    sourceUrl: CAMBRIDGE_B2_FIRST_SOURCE_URL,
    examFamily: CAMBRIDGE_B2_FIRST,
  }));
}

const readingAndUseOfEnglish: CambridgeSeed[] = [
  {
    component: "Reading & Use of English", part: "Part 1", questionType: "Multiple-choice cloze",
    topic: "B2 First · Reading Part 1", difficulty: "情境",
    stem: "The museum's new exhibition has attracted a great deal of ___ from local schools.",
    options: ["interest", "attention", "notice", "regard"], answer: 0,
    explanation: "The fixed collocation is ‘attract interest from’; the other nouns do not fit this pattern as naturally.",
    trap: "先辨識動詞與名詞的搭配，再依句意排除看似相近的字。",
  },
  {
    component: "Reading & Use of English", part: "Part 1", questionType: "Multiple-choice cloze",
    topic: "B2 First · Reading Part 1", difficulty: "情境",
    stem: "Although the route was longer, it proved to be a more ___ alternative during the winter months.",
    options: ["reliable", "sensible", "faithful", "steady"], answer: 0,
    explanation: "A route that can be depended on is reliable; the sentence focuses on consistent performance in winter.",
    trap: "Sensible describes a decision or person, while reliable describes something that works dependably.",
  },
  {
    component: "Reading & Use of English", part: "Part 1", questionType: "Multiple-choice cloze",
    topic: "B2 First · Reading Part 1", difficulty: "進階",
    stem: "The research team carried ___ a second experiment to test whether the result could be repeated.",
    options: ["out", "up", "off", "through"], answer: 0,
    explanation: "Carry out means to perform or complete a task such as an experiment.",
    trap: "片語動詞要整體理解；carry through means complete something difficult, but the object and context here favour carry out.",
  },
  {
    component: "Reading & Use of English", part: "Part 1", questionType: "Multiple-choice cloze",
    topic: "B2 First · Reading Part 1", difficulty: "進階",
    stem: "The speaker's conclusion was based on evidence that was far from ___.",
    options: ["conclusive", "concluding", "concluded", "conclusion"], answer: 0,
    explanation: "Conclusive is the adjective meaning decisive or sufficient to prove something.",
    trap: "先判斷空格需要形容詞，再區分 conclusive 與其他同字根形式。",
  },
  {
    component: "Reading & Use of English", part: "Part 2", questionType: "Open cloze · guided practice",
    topic: "B2 First · Reading Part 2", difficulty: "進階",
    stem: "The course was designed ___ response to requests from adult learners.",
    options: ["in", "on", "at", "by"], answer: 0,
    explanation: "The fixed expression is ‘in response to’, meaning as an answer to something.",
    trap: "這類題目要優先辨識固定介系詞搭配，而不是只依中文直譯。",
  },
  {
    component: "Reading & Use of English", part: "Part 2", questionType: "Open cloze · guided practice",
    topic: "B2 First · Reading Part 2", difficulty: "情境",
    stem: "No sooner had the doors opened ___ the first visitors began to arrive.",
    options: ["than", "when", "that", "as"], answer: 0,
    explanation: "No sooner ... than is a fixed paired structure used to show that one event happened immediately after another.",
    trap: "不要將 no sooner ... than 與 hardly ... when 的搭配混用。",
  },
  {
    component: "Reading & Use of English", part: "Part 2", questionType: "Open cloze · guided practice",
    topic: "B2 First · Reading Part 2", difficulty: "進階",
    stem: "The manager asked whether the report had been sent, but nobody knew ___ had sent it.",
    options: ["who", "which", "what", "whose"], answer: 0,
    explanation: "Who is the subject of the embedded question and refers to a person.",
    trap: "嵌入疑問句仍要看空格在子句中扮演的功能；這裡需要人作主詞。",
  },
  {
    component: "Reading & Use of English", part: "Part 2", questionType: "Open cloze · guided practice",
    topic: "B2 First · Reading Part 2", difficulty: "基礎",
    stem: "The device is small enough to fit ___ a jacket pocket.",
    options: ["into", "at", "by", "with"], answer: 0,
    explanation: "Fit into describes movement or placement inside a space.",
    trap: "fit in 與 fit into 都可能出現，但此句後面有具體容器 a jacket pocket，into 最精準。",
  },
  {
    component: "Reading & Use of English", part: "Part 3", questionType: "Word formation · guided practice",
    topic: "B2 First · Reading Part 3", difficulty: "進階",
    stem: "The proposal was rejected because its financial ___ were too optimistic. (ASSUME)",
    options: ["assumptions", "assumptives", "assumingly", "assumed"], answer: 0,
    explanation: "The plural noun assumptions names the ideas or conditions used as a basis for calculation.",
    trap: "先看句法位置：financial 後需要名詞，而語意要求多項前提。",
  },
  {
    component: "Reading & Use of English", part: "Part 3", questionType: "Word formation · guided practice",
    topic: "B2 First · Reading Part 3", difficulty: "進階",
    stem: "The new timetable should make the service considerably more ___. (EFFICIENCY)",
    options: ["efficient", "efficiency", "efficiently", "efficience"], answer: 0,
    explanation: "After more, the sentence needs the adjective efficient to describe the service.",
    trap: "more 後不一定接副詞；此處 be more ___ 是形容詞補語。",
  },
  {
    component: "Reading & Use of English", part: "Part 3", questionType: "Word formation · guided practice",
    topic: "B2 First · Reading Part 3", difficulty: "情境",
    stem: "The speaker gave a clear and highly ___ explanation of the process. (INFORM)",
    options: ["informative", "information", "informed", "informing"], answer: 0,
    explanation: "An informative explanation provides useful information, so the adjective informative fits the meaning.",
    trap: "Informed describes a person or decision with knowledge; informative describes something that gives knowledge. ",
  },
  {
    component: "Reading & Use of English", part: "Part 3", questionType: "Word formation · guided practice",
    topic: "B2 First · Reading Part 3", difficulty: "進階",
    stem: "The report highlights the growing ___ of remote collaboration tools. (POPULAR)",
    options: ["popularity", "popularise", "popularly", "popularisation"], answer: 0,
    explanation: "The growing ___ of something requires the noun popularity.",
    trap: "the growing + noun 是常見結構；不要被字尾相近的動詞或副詞干擾。",
  },
  {
    component: "Reading & Use of English", part: "Part 4", questionType: "Key word transformation · guided practice",
    topic: "B2 First · Reading Part 4", difficulty: "進階",
    stem: "It wasn't necessary for Maya to attend the meeting. (NEED)\nMaya ___ attend the meeting.",
    options: ["didn't need to", "needn't have", "mustn't", "wouldn't need"], answer: 0,
    explanation: "Didn't need to expresses that attendance was not necessary; the sentence gives no indication that she attended.",
    trap: "Needn't have attended means she attended unnecessarily, which is a different meaning. ",
  },
  {
    component: "Reading & Use of English", part: "Part 4", questionType: "Key word transformation · guided practice",
    topic: "B2 First · Reading Part 4", difficulty: "進階",
    stem: "The last time I visited the gallery was two years ago. (BEEN)\nI ___ the gallery for two years.",
    options: ["haven't been to", "didn't go to", "wasn't going to", "wouldn't be in"], answer: 0,
    explanation: "The present perfect with for describes a state continuing up to now: I haven't been to the gallery for two years.",
    trap: "Two years ago 指過去時間點，但改寫句需要連結到現在的期間。",
  },
  {
    component: "Reading & Use of English", part: "Part 4", questionType: "Key word transformation · guided practice",
    topic: "B2 First · Reading Part 4", difficulty: "情境",
    stem: "The team postponed the launch because the testing was incomplete. (PUT)\nThe team ___ because the testing was incomplete.",
    options: ["put off the launch", "put the launch out", "put up the launch", "put the launch away"], answer: 0,
    explanation: "Put off means postpone, so it preserves the meaning of the original sentence.",
    trap: "片語動詞的介系詞不可任意替換；put out 通常指熄滅或發布。",
  },
  {
    component: "Reading & Use of English", part: "Part 5", questionType: "Multiple choice reading",
    topic: "B2 First · Reading Part 5", difficulty: "情境",
    stimulus: "Urban gardens are often praised for producing food close to consumers. Their less obvious benefit is that they create places where neighbours can meet, share practical knowledge and take responsibility for a common space. In several projects, the social value of the garden has proved more lasting than the harvest itself.",
    stem: "What is the writer's main point about urban gardens?",
    options: ["Their social benefits can be more significant than their food production.", "They are the cheapest way to supply cities with vegetables.", "Most neighbours prefer gardening to other community activities.", "Their main purpose should be to teach professional farming."], answer: 0,
    explanation: "The passage contrasts food production with the less obvious, longer-lasting social value of shared gardens.",
    trap: "不要只抓第一句的 food；後文明確把重點轉到 neighbours、knowledge 與 shared responsibility。",
  },
  {
    component: "Reading & Use of English", part: "Part 5", questionType: "Multiple choice reading",
    topic: "B2 First · Reading Part 5", difficulty: "進階",
    stimulus: "When I began repairing old radios, I expected the technical challenge to be the most rewarding part. Instead, I became fascinated by the stories attached to each object: who had bought it, where it had stood and why someone had kept it for decades. The repairs gave me access to histories that were never written down.",
    stem: "What surprised the writer about repairing old radios?",
    options: ["The personal histories connected with them were especially rewarding.", "The technical work was more difficult than expected.", "Most owners wanted to replace rather than repair them.", "The radios were usually older than their owners remembered."], answer: 0,
    explanation: "The writer expected technical work to be most rewarding but was surprised by the stories attached to the objects.",
    trap: "文章不是說技術很困難，而是說作者原本以為技術挑戰會最有收穫。",
  },
  {
    component: "Reading & Use of English", part: "Part 5", questionType: "Multiple choice reading",
    topic: "B2 First · Reading Part 5", difficulty: "情境",
    stimulus: "The study did not claim that short breaks automatically improve every kind of work. It found that breaks were most useful when they changed the worker's mental activity, for example by involving movement or a different type of problem. Simply switching from one screen to another had little measurable effect.",
    stem: "According to the study, when are breaks most useful?",
    options: ["When they involve a meaningful change of activity.", "When they last exactly five minutes.", "When workers continue looking at a screen.", "When they are taken only after difficult tasks."], answer: 0,
    explanation: "The study links useful breaks to a change in mental activity rather than to a fixed length or screen switch.",
    trap: "文章沒有給出固定分鐘數；要找的是 breaks 改變 mental activity 的條件。",
  },
  {
    component: "Reading & Use of English", part: "Part 6", questionType: "Gapped text",
    topic: "B2 First · Reading Part 6", difficulty: "進階",
    stimulus: "A: Learning to cook from scratch can seem inefficient at first.\nB: ___\nC: With practice, however, the same actions become quicker and more intuitive.\nD: This is why beginners often rely on prepared ingredients.",
    stem: "Which sentence best fits the gap?",
    options: ["A beginner must think about every small action and decision.", "Professional chefs never use prepared ingredients.", "Recipes are always shorter than people expect.", "The kitchen is usually the quietest room in a home."], answer: 0,
    explanation: "The following sentence begins ‘With practice’, so the gap should introduce the slow, conscious effort of a beginner.",
    trap: "銜接題要看前後語意與指涉；with practice 明確暗示前文是尚未熟練的狀態。",
  },
  {
    component: "Reading & Use of English", part: "Part 6", questionType: "Gapped text",
    topic: "B2 First · Reading Part 6", difficulty: "進階",
    stimulus: "A: Public speaking is often described as a performance.\nB: ___\nC: The most convincing speakers, therefore, sound prepared without appearing to recite.",
    stem: "Which sentence best completes the paragraph?",
    options: ["Yet successful speakers are also responding to the audience in real time.", "Audiences always prefer speakers who use complicated words.", "A speech can only be delivered successfully in a theatre.", "Rehearsal is unnecessary once a speaker knows the topic."], answer: 0,
    explanation: "The final sentence contrasts sounding prepared with sounding recited, so the missing idea should connect performance with live audience response.",
    trap: "不要只看單句合理性；要讓 gap 同時承接 performance 並引出 prepared but natural。",
  },
  {
    component: "Reading & Use of English", part: "Part 6", questionType: "Gapped text",
    topic: "B2 First · Reading Part 6", difficulty: "情境",
    stimulus: "A: Maps are usually treated as objective descriptions of places.\nB: ___\nC: The choice of what to include can influence how a reader understands a region.",
    stem: "Which sentence best fits the gap?",
    options: ["In fact, every map reflects decisions about what matters.", "For that reason, maps should never be used for travel.", "Most maps are printed on exactly the same size of paper.", "A compass is more useful than any map."], answer: 0,
    explanation: "The phrase ‘In fact’ challenges the assumption in A and prepares for C's point about selection and influence.",
    trap: "注意轉折語氣與代名詞；這裡需要能修正 objective 的前提，而不是離題資訊。",
  },
  {
    component: "Reading & Use of English", part: "Part 7", questionType: "Multiple matching",
    topic: "B2 First · Reading Part 7", difficulty: "情境",
    stimulus: "A: Lina chose the course because she wanted structured feedback on her design work.\nB: Omar joined after a colleague recommended the tutor's practical approach.\nC: Priya valued the chance to work with people from industries different from her own.\nD: Theo mainly wanted a qualification that would support an application for promotion.",
    stem: "Which learner was chiefly motivated by meeting people with different professional backgrounds?",
    options: ["Lina", "Omar", "Priya", "Theo"], answer: 2,
    explanation: "Priya explicitly valued working with people from industries different from her own.",
    trap: "Multiple matching 要找與問題完全對應的動機，而不是只看到 course、tutor 或 qualification 等共同字詞。",
  },
  {
    component: "Reading & Use of English", part: "Part 7", questionType: "Multiple matching",
    topic: "B2 First · Reading Part 7", difficulty: "進階",
    stimulus: "A: The café is busiest at lunchtime, but the staff remain friendly and efficient.\nB: The café is small and quiet, which makes it suitable for reading or working.\nC: The café offers unusual vegetarian dishes, though service can be slow.\nD: The café is open late and is popular with people attending nearby events.",
    stem: "Which café is recommended mainly because of its atmosphere for concentrating?",
    options: ["A", "B", "C", "D"], answer: 1,
    explanation: "B is described as small and quiet, making it suitable for reading or working.",
    trap: "把 suitability for concentrating 與 friendly service、late opening 或 unusual dishes 分開。",
  },
  {
    component: "Reading & Use of English", part: "Part 7", questionType: "Multiple matching",
    topic: "B2 First · Reading Part 7", difficulty: "情境",
    stimulus: "A: The exhibition is strongest when it shows how the artist's ideas developed over time.\nB: The exhibition is memorable for its interactive technology.\nC: The exhibition is valuable because it includes several works rarely shown in public.\nD: The exhibition is most enjoyable when visitors already know the artist's biography.",
    stem: "Which comment focuses on the rarity of the works on display?",
    options: ["A", "B", "C", "D"], answer: 2,
    explanation: "C directly states that the value comes from including works rarely shown in public.",
    trap: "rarely shown 對應 rarity；不要被 memorable、ideas 或 biography 等其他評價焦點干擾。",
  },
];

const listening: CambridgeSeed[] = [
  {
    component: "Listening", part: "Part 1", questionType: "Multiple-choice short extracts",
    topic: "B2 First · Listening Part 1", difficulty: "情境",
    stem: "What does the woman say about the new timetable?",
    options: ["It is more convenient than she expected.", "It has made her journey considerably longer.", "It was designed without asking passengers.", "It is difficult to understand at the station."], answer: 0,
    audioScript: "I was worried the new timetable would mean changing trains, but the opposite has happened. I can now leave ten minutes later and still arrive before nine, so it is actually more convenient than the old one.",
    explanation: "She expected a problem but says she can leave later and arrive earlier, so the timetable is more convenient than expected.",
    trap: "聽力 Part 1 常用轉折修正預期；注意 but the opposite has happened 與 actually。",
  },
  {
    component: "Listening", part: "Part 1", questionType: "Multiple-choice short extracts",
    topic: "B2 First · Listening Part 1", difficulty: "進階",
    stem: "Why did the man change his presentation?",
    options: ["The audience already knew the technical background.", "He had forgotten to prepare enough slides.", "The organiser shortened the event.", "His colleague asked him to use more examples."], answer: 0,
    audioScript: "At first I planned to spend half the talk explaining the basic terminology. Then I saw the list of attendees and realised most of them work with this technology every day. I cut that section and used the time for the results instead.",
    explanation: "He changed the presentation after realising the audience already knew the technical background.",
    trap: "不要把 cut that section 誤聽成忘了準備；改動是依聽眾程度做的。",
  },
  {
    component: "Listening", part: "Part 1", questionType: "Multiple-choice short extracts",
    topic: "B2 First · Listening Part 1", difficulty: "情境",
    stem: "What is the speaker's attitude towards the book?",
    options: ["Generally positive despite one reservation.", "Completely disappointed by its conclusion.", "Uncertain whether it was written for adults.", "Impressed mainly by its illustrations."], answer: 0,
    audioScript: "The middle chapters moved a little slowly for me, but the final section brought everything together brilliantly. I would not call it flawless, yet I finished it feeling that the author had achieved what she set out to do.",
    explanation: "The speaker identifies a weakness but ends with a positive overall judgement, so the attitude is generally positive with a reservation.",
    trap: "but、yet 與 not flawless 表示保留意見，不等於完全失望。",
  },
  {
    component: "Listening", part: "Part 2", questionType: "Sentence completion",
    topic: "B2 First · Listening Part 2", difficulty: "基礎",
    stem: "The community centre's Saturday workshop begins at ___.",
    options: ["9:30", "10:00", "10:30", "11:00"], answer: 2,
    audioScript: "The doors will open at ten, giving participants time to register. The workshop itself starts half an hour later, at ten thirty, and should finish shortly after midday.",
    explanation: "The speaker distinguishes the doors opening at ten from the workshop starting at ten thirty.",
    trap: "聽到第一個時間不要立即作答；sentence completion 常在後句修正真正答案。",
  },
  {
    component: "Listening", part: "Part 2", questionType: "Sentence completion",
    topic: "B2 First · Listening Part 2", difficulty: "進階",
    stem: "Visitors are asked to leave large bags in the ___ beside the entrance.",
    options: ["office", "locker area", "café", "lecture room"], answer: 1,
    audioScript: "For safety reasons, large bags cannot be taken into the gallery. Please use the locker area beside the entrance; the office is only for staff enquiries.",
    explanation: "The bag storage location is the locker area beside the entrance.",
    trap: "辦公室 office 也被提到，但它被明確限定為 staff enquiries 的地點。",
  },
  {
    component: "Listening", part: "Part 2", questionType: "Sentence completion",
    topic: "B2 First · Listening Part 2", difficulty: "情境",
    stem: "The speaker recommends booking online because the event often becomes ___.",
    options: ["expensive", "uncrowded", "fully booked", "cancelled"], answer: 2,
    audioScript: "There is no extra charge for booking on the website, and it is worth doing because the evening sessions are often fully booked by Thursday. People who turn up without a reservation may have to wait.",
    explanation: "The reason for booking online is that evening sessions are often fully booked.",
    trap: "worth doing 是建議語氣，真正原因在 because 後的 fully booked。",
  },
  {
    component: "Listening", part: "Part 3", questionType: "Multiple-choice interview",
    topic: "B2 First · Listening Part 3", difficulty: "進階",
    stem: "What does the researcher say was the most difficult part of the project?",
    options: ["Recruiting suitable participants.", "Explaining the results to the public.", "Finding enough equipment.", "Working within a small team."], answer: 0,
    audioScript: "The equipment was available and the analysis went smoothly. Our real difficulty was finding participants who met all the criteria and were willing to return for a second interview. Once that group was in place, the rest of the project was manageable.",
    explanation: "The researcher explicitly identifies finding suitable participants willing to return as the real difficulty.",
    trap: "先排除 speaker 說順利或 available 的項目，再抓 real difficulty 後的資訊。",
  },
  {
    component: "Listening", part: "Part 3", questionType: "Multiple-choice interview",
    topic: "B2 First · Listening Part 3", difficulty: "情境",
    stem: "How did the speaker's opinion of remote work change?",
    options: ["She became more aware of its practical advantages.", "She decided it was unsuitable for creative jobs.", "She found it less flexible than office work.", "She began to prefer working without colleagues."], answer: 0,
    audioScript: "I used to think working from home would make collaboration impossible. After trying it, I realised that some planning tasks were actually easier online. I still miss spontaneous conversations, but I no longer see remote work as a temporary compromise.",
    explanation: "Her view became more positive after discovering practical advantages, although she still misses spontaneous conversations.",
    trap: "still miss 表示保留，不會推翻 no longer see ... as a compromise 的整體轉變。",
  },
  {
    component: "Listening", part: "Part 4", questionType: "Multiple matching · discussion",
    topic: "B2 First · Listening Part 4", difficulty: "進階",
    stem: "Which speaker mentions learning from an unexpected mistake?",
    options: ["Speaker 1", "Speaker 2", "Speaker 3", "Speaker 4"], answer: 2,
    audioScript: "Speaker 1: I learnt most from observing how an experienced colleague handled a difficult customer. Speaker 2: The useful lesson was planning the handover before the deadline. Speaker 3: I made a calculation error no one noticed at first, and checking it later taught me to question results that look unusually good. Speaker 4: My main lesson was that clear documentation saves time.",
    explanation: "Speaker 3 describes a calculation error that led to an unexpected lesson about questioning unusually good results.",
    trap: "每位 speaker 都談 learning；要精準對應 unexpected mistake，而非一般經驗。",
  },
  {
    component: "Listening", part: "Part 4", questionType: "Multiple matching · discussion",
    topic: "B2 First · Listening Part 4", difficulty: "情境",
    stem: "Which speaker focuses on the value of documenting a process?",
    options: ["Speaker 1", "Speaker 2", "Speaker 3", "Speaker 4"], answer: 3,
    audioScript: "Speaker 1: Feedback from users changed how we tested the service. Speaker 2: The important discovery was that a short break improved our decisions. Speaker 3: A failed prediction reminded me to check the assumptions behind a model. Speaker 4: Writing down each stage seemed slow, but it meant that another person could repeat the process without asking us the same questions.",
    explanation: "Speaker 4 links writing down each stage with making the process repeatable for another person.",
    trap: "focus on value 要找結果與用途；Speaker 4 明確說明 documenting 帶來可重複與減少詢問。",
  },
];

export const CAMBRIDGE_B2_FIRST_QUESTIONS: Question[] = [
  ...makeQuestions("RUE", readingAndUseOfEnglish),
  ...makeQuestions("LIS", listening),
];
