import type { Question } from "./questions";

export const ENGLISH_B2_SUBJECT = "英文能力｜CEFR B2";
export const CEFR_B2_SOURCE_URL = "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors";
const CEFR_B2_SOURCE = "CEFR B2 能力描述；本站依公開框架自編";

type Seed = {
  stem: string;
  correct: string;
  distractors: [string, string, string];
  topic: string;
  explanation: string;
};

function rotateOptions(seed: Seed, index: number): { options: [string, string, string, string]; answer: number } {
  const options = [seed.correct, ...seed.distractors];
  const offset = index % 4;
  const rotated = [...options.slice(offset), ...options.slice(0, offset)] as [string, string, string, string];
  return { options: rotated, answer: (4 - offset) % 4 };
}

function makeQuestions(prefix: string, seeds: Seed[], difficulty: Question["difficulty"]): Question[] {
  return seeds.map((seed, index) => {
    const { options, answer } = rotateOptions(seed, index);
    return {
      id: `B2-ENG-${prefix}-${String(index + 1).padStart(3, "0")}`,
      level: "中級",
      subject: ENGLISH_B2_SUBJECT,
      topic: seed.topic,
      difficulty,
      stem: seed.stem,
      options,
      answer,
      explanation: `${seed.explanation} 此題對應 CEFR B2 的${seed.topic}能力。`,
      trap: "先從語境、語氣與句法功能判斷，再排除只在局部看似合理但不符合完整語意的選項。",
      source: CEFR_B2_SOURCE,
      sourceUrl: CEFR_B2_SOURCE_URL,
    };
  });
}

const vocabulary: Seed[] = [
  { stem: "The committee decided to ___ the proposal until more evidence was available.", correct: "defer", distractors: ["infer", "confer", "refer"], topic: "Vocabulary in context", explanation: "Defer means to postpone a decision or action; the sentence requires postponement." },
  { stem: "The new policy is intended to ___ unnecessary administrative costs.", correct: "eliminate", distractors: ["compile", "allocate", "illustrate"], topic: "Vocabulary in context", explanation: "Eliminate means remove completely, which fits reducing unnecessary costs." },
  { stem: "Her explanation was clear and ___, so everyone understood the procedure.", correct: "concise", distractors: ["reluctant", "ambiguous", "consecutive"], topic: "Vocabulary in context", explanation: "Concise describes communication that is brief without losing the necessary meaning." },
  { stem: "The report draws attention to a ___ gap between policy and practice.", correct: "substantial", distractors: ["fragile", "temporary", "obedient"], topic: "Vocabulary in context", explanation: "Substantial means considerable or significant, appropriate for a large gap." },
  { stem: "The researcher remained ___ about the result until the sample was independently checked.", correct: "cautious", distractors: ["delighted", "arbitrary", "conventional"], topic: "Vocabulary in context", explanation: "Cautious means careful to avoid risk, matching the need for verification." },
  { stem: "The witness gave a ___ account of what happened, including times and locations.", correct: "detailed", distractors: ["vague", "irrelevant", "artificial"], topic: "Vocabulary in context", explanation: "Detailed means containing many relevant facts, as indicated by times and locations." },
  { stem: "The two studies reached ___ conclusions despite using different methods.", correct: "consistent", distractors: ["invisible", "contemporary", "scarce"], topic: "Vocabulary in context", explanation: "Consistent conclusions agree with each other." },
  { stem: "The manager tried to ___ the conflict before it affected the whole team.", correct: "resolve", distractors: ["provoke", "exclude", "withdraw"], topic: "Vocabulary in context", explanation: "Resolve means settle a problem or disagreement." },
  { stem: "The museum is working to ___ the building without changing its historic character.", correct: "preserve", distractors: ["overlook", "speculate", "distribute"], topic: "Vocabulary in context", explanation: "Preserve means protect something from damage or change." },
  { stem: "The figures should be treated as ___ because the survey included only twenty participants.", correct: "tentative", distractors: ["permanent", "mandatory", "identical"], topic: "Vocabulary in context", explanation: "Tentative means not yet certain or final." },
  { stem: "The course aims to ___ students with the skills needed for independent research.", correct: "equip", distractors: ["deprive", "interrupt", "confine"], topic: "Vocabulary in context", explanation: "Equip means provide someone with a useful skill or resource." },
  { stem: "The proposal was rejected because its financial assumptions were not ___.", correct: "realistic", distractors: ["superficial", "punctual", "sensitive"], topic: "Vocabulary in context", explanation: "Realistic assumptions are practical and compatible with actual conditions." },
  { stem: "The speaker used an example to ___ the difference between the two approaches.", correct: "clarify", distractors: ["constrain", "retain", "postpone"], topic: "Vocabulary in context", explanation: "Clarify means make an idea easier to understand." },
  { stem: "The company must ___ with the safety regulations before opening the facility.", correct: "comply", distractors: ["object", "presume", "retain"], topic: "Vocabulary in context", explanation: "Comply with means act according to a rule or requirement." },
  { stem: "The article provides a ___ overview rather than focusing on one isolated event.", correct: "comprehensive", distractors: ["accidental", "predictable", "hostile"], topic: "Vocabulary in context", explanation: "Comprehensive means covering all or most relevant aspects." },
  { stem: "The team made a ___ attempt to reduce energy consumption, but the effect was limited.", correct: "deliberate", distractors: ["random", "fragile", "verbal"], topic: "Vocabulary in context", explanation: "Deliberate means planned and intentional." },
  { stem: "The evidence is ___ with the explanation offered by the original report.", correct: "compatible", distractors: ["punctual", "scarce", "transparent"], topic: "Vocabulary in context", explanation: "Compatible evidence does not conflict with the explanation." },
  { stem: "The survey revealed a ___ preference for flexible working hours among respondents.", correct: "prevalent", distractors: ["optional", "rigid", "isolated"], topic: "Vocabulary in context", explanation: "Prevalent means common or widespread." },
  { stem: "The editor asked the author to ___ the claim because it was stronger than the evidence.", correct: "qualify", distractors: ["accelerate", "imitate", "commute"], topic: "Vocabulary in context", explanation: "Qualify a claim means limit or modify it so it is more accurate." },
  { stem: "The project was delayed by a ___ shortage of qualified technicians.", correct: "temporary", distractors: ["symbolic", "permanent", "deliberate"], topic: "Vocabulary in context", explanation: "Temporary means lasting for a limited period, which explains a delay rather than a permanent condition." },
  { stem: "The instructions are ___ enough for users to follow without technical support.", correct: "straightforward", distractors: ["controversial", "excessive", "obsolete"], topic: "Vocabulary in context", explanation: "Straightforward means simple and easy to understand." },
  { stem: "The journalist was careful not to ___ the interviewee's words out of context.", correct: "distort", distractors: ["assemble", "restore", "consult"], topic: "Vocabulary in context", explanation: "Distort means represent something inaccurately or misleadingly." },
  { stem: "The agreement is legally ___ only after both parties sign it.", correct: "binding", distractors: ["casual", "distinct", "optional"], topic: "Vocabulary in context", explanation: "Binding describes an agreement that creates an obligation." },
  { stem: "The findings are ___ to several other regions, although local conditions differ.", correct: "relevant", distractors: ["vertical", "fragile", "incidental"], topic: "Vocabulary in context", explanation: "Relevant means connected with the matter being considered." },
  { stem: "The training helped staff ___ potential risks before they became serious problems.", correct: "identify", distractors: ["celebrate", "postpone", "exclude"], topic: "Vocabulary in context", explanation: "Identify means recognize or establish what something is." },
];

const grammar: Seed[] = [
  { stem: "By the time the meeting starts, the director ___ the revised figures.", correct: "will have reviewed", distractors: ["reviews", "reviewed", "has reviewing"], topic: "Grammar and sentence control", explanation: "The future perfect describes an action completed before a future time." },
  { stem: "If the data ___ more reliable, we could draw a stronger conclusion.", correct: "were", distractors: ["are", "will be", "have been"], topic: "Grammar and sentence control", explanation: "The second conditional uses a past form in the if-clause for a hypothetical present situation." },
  { stem: "The report, ___ was published last week, has already influenced the debate.", correct: "which", distractors: ["what", "where", "whose"], topic: "Grammar and sentence control", explanation: "Which introduces a non-defining relative clause referring to the report." },
  { stem: "The equipment needs ___ before it can be used safely.", correct: "to be inspected", distractors: ["inspecting it", "inspect", "to inspect it by"], topic: "Grammar and sentence control", explanation: "After needs in this passive meaning, to be inspected expresses the required action on the equipment." },
  { stem: "She denied ___ the confidential file to anyone outside the team.", correct: "having sent", distractors: ["to send", "send", "that sending"], topic: "Grammar and sentence control", explanation: "Deny is followed by a gerund; having sent emphasizes that the alleged action occurred earlier." },
  { stem: "Only after the audit ___ the scale of the problem become clear.", correct: "did", distractors: ["has", "was", "had"], topic: "Grammar and sentence control", explanation: "Negative or restrictive adverbials at the beginning trigger subject–auxiliary inversion." },
  { stem: "The software is designed to prevent users ___ the same form twice.", correct: "from submitting", distractors: ["to submit", "submit", "for submitting"], topic: "Grammar and sentence control", explanation: "Prevent is followed by object plus from and a gerund." },
  { stem: "The more carefully the instructions are written, ___ the process will be.", correct: "the smoother", distractors: ["smoother than", "the smoothest", "smoothly"], topic: "Grammar and sentence control", explanation: "The correlative comparative pattern is the more..., the + comparative." },
  { stem: "It is essential that every applicant ___ proof of identity.", correct: "provide", distractors: ["provides", "provided", "will providing"], topic: "Grammar and sentence control", explanation: "Formal mandative constructions use the base form after essential that." },
  { stem: "The researcher suggested that the experiment ___ under controlled conditions.", correct: "be repeated", distractors: ["is repeating", "repeated to", "will repeated"], topic: "Grammar and sentence control", explanation: "Suggest that in formal English can take a passive mandative subjunctive: be repeated." },
  { stem: "The policy was introduced with a view to ___ workplace accidents.", correct: "reducing", distractors: ["reduce", "reduced", "have reduced"], topic: "Grammar and sentence control", explanation: "With a view to is followed by a gerund because to functions as a preposition." },
  { stem: "Having ___ the contract, both parties received a digital copy.", correct: "signed", distractors: ["signing to", "been sign", "to sign"], topic: "Grammar and sentence control", explanation: "A perfect participle clause uses having plus the past participle for an earlier completed action." },
  { stem: "The figures are believed ___ by an error in the original spreadsheet.", correct: "to have been affected", distractors: ["affecting", "to affect by", "having affect"], topic: "Grammar and sentence control", explanation: "The passive reporting structure with an earlier effect requires to have been affected." },
  { stem: "Despite ___ several warnings, the company continued the unsafe practice.", correct: "having received", distractors: ["receive", "to receiving", "received to"], topic: "Grammar and sentence control", explanation: "Despite is a preposition and takes a noun or gerund phrase; perfect form marks the earlier warnings." },
  { stem: "The candidate spoke as though she ___ the issue personally.", correct: "had investigated", distractors: ["investigates", "will investigate", "has investigating"], topic: "Grammar and sentence control", explanation: "As though referring to an apparently earlier action uses the past perfect." },
  { stem: "No sooner ___ the announcement made than questions began to arise.", correct: "had they made", distractors: ["they had made", "did they making", "they make"], topic: "Grammar and sentence control", explanation: "No sooner at the beginning requires inversion and is followed by than." },
  { stem: "The committee could not agree on ___ should lead the next phase.", correct: "who", distractors: ["which that", "what person did", "whose one"], topic: "Grammar and sentence control", explanation: "Who functions as the subject of the embedded question." },
  { stem: "The proposal is worth ___ before a final decision is made.", correct: "considering", distractors: ["to consider it", "considered to", "consider"], topic: "Grammar and sentence control", explanation: "Worth is followed by a gerund, not an infinitive." },
  { stem: "The findings would have been different if the researchers ___ a larger sample.", correct: "had used", distractors: ["use", "would use", "have using"], topic: "Grammar and sentence control", explanation: "The third conditional uses past perfect in the if-clause for an unreal past condition." },
  { stem: "The manager had the documents ___ by an independent lawyer.", correct: "checked", distractors: ["checking", "to checking", "check by"], topic: "Grammar and sentence control", explanation: "Have something done uses have plus object plus past participle." },
  { stem: "There is little point in ___ the deadline if the quality declines.", correct: "extending", distractors: ["extend", "to extending it", "extended"], topic: "Grammar and sentence control", explanation: "Point in is followed by a gerund phrase." },
  { stem: "The survey results indicate that consumers are becoming ___ price-sensitive.", correct: "increasingly", distractors: ["increase", "increased", "increasing"], topic: "Grammar and sentence control", explanation: "Increasingly is the adverb modifying the adjective price-sensitive." },
  { stem: "The device will operate efficiently provided that it ___ regularly.", correct: "is maintained", distractors: ["maintains", "will maintain", "maintained it"], topic: "Grammar and sentence control", explanation: "Provided that introduces a real condition; the device receives maintenance, so passive voice is needed." },
  { stem: "The speaker's argument is not so much incorrect ___ incomplete.", correct: "as", distractors: ["than", "but", "that"], topic: "Grammar and sentence control", explanation: "Not so much X as Y contrasts the degree or type of two descriptions." },
  { stem: "The team is expected ___ its recommendations by Friday.", correct: "to publish", distractors: ["publishing to", "publish it to", "to publishing"], topic: "Grammar and sentence control", explanation: "The passive reporting structure expected to is followed by the infinitive." },
];

const reading: Seed[] = [
  { stem: "Read: 'The library extended its opening hours, but visitor numbers rose only slightly. A follow-up survey found that most residents were unaware of the change.' What is the main explanation for the limited increase?", correct: "People did not know about the new hours.", distractors: ["The library reduced its collection.", "Visitors disliked the building's design.", "The survey was cancelled."], topic: "Reading for main ideas", explanation: "The survey directly identifies lack of awareness as the reason visitor numbers changed little." },
  { stem: "Read: 'Although the pilot reduced delivery times, it required twice as many staff during peak periods. Managers therefore postponed expansion.' What influenced the decision?", correct: "The staffing cost of scaling up.", distractors: ["A fall in customer demand.", "A legal ban on delivery.", "A failure to reduce delivery times."], topic: "Reading for inference", explanation: "The benefit was real, but the extra staffing requirement made expansion impractical at that stage." },
  { stem: "Read: 'The article does not reject remote work; instead, it argues that its success depends on clear communication routines and suitable tasks.' Which position does the author take?", correct: "Remote work can work under the right conditions.", distractors: ["Remote work is always ineffective.", "Only technical tasks can be done remotely.", "Communication is unnecessary online."], topic: "Reading for writer attitude", explanation: "The contrast marker instead signals a qualified, conditional position rather than outright rejection." },
  { stem: "Read: 'The museum's attendance recovered after free entry was introduced on Fridays, though the director warns that the figures may reflect a temporary novelty effect.' What caution is expressed?", correct: "The increase may not continue.", distractors: ["Free entry was legally prohibited.", "Friday was the quietest day before the change.", "The museum stopped measuring attendance."], topic: "Reading for inference", explanation: "A novelty effect means initial interest may fade, so the increase is not necessarily permanent." },
  { stem: "Read: 'The report uses the phrase “associated with” rather than “caused by” when discussing exercise and wellbeing.' Why?", correct: "The evidence shows a relationship but not definite causation.", distractors: ["The two variables were never measured.", "The report is a work of fiction.", "Exercise and wellbeing are identical concepts."], topic: "Reading for precise meaning", explanation: "Associated with is deliberately more cautious than caused by and avoids claiming proof of causality." },
  { stem: "Read: 'When the first prototype failed, the engineers did not discard the project. They used the test results to redesign the cooling system.' What does this show?", correct: "Failure was used as feedback.", distractors: ["The prototype was never tested.", "The engineers abandoned the objective.", "The cooling system was already perfect."], topic: "Reading for main ideas", explanation: "The second sentence explains that the failure informed a redesign." },
  { stem: "Read: 'The town's new cycle lanes are popular with commuters, but shop owners report fewer short visits by drivers. The council is reviewing loading arrangements.' What issue is being addressed?", correct: "How to balance access with safer streets.", distractors: ["Whether cycling is physically possible.", "How to close all local shops.", "Why commuters refuse public transport."], topic: "Reading for synthesis", explanation: "The passage presents a benefit and a commercial concern, followed by a review of access arrangements." },
  { stem: "Read: 'The author cites three small studies and notes that their participants were self-selected. The conclusion is described as promising rather than conclusive.' How strong is the evidence?", correct: "Encouraging but limited.", distractors: ["Definitive and universal.", "Entirely irrelevant.", "Based on a national census."], topic: "Reading for writer attitude", explanation: "Small self-selected samples justify a cautious interpretation, not a final conclusion." },
  { stem: "Read: 'The software update removed several visible features. According to the designer, those features had been used by less than one percent of customers and slowed the interface for everyone.' What was the rationale?", correct: "Prioritising overall performance over rare features.", distractors: ["Making the software harder for every user.", "Adding more features for specialist users.", "Responding to a shortage of customer data."], topic: "Reading for inference", explanation: "The designer weighed low usage against a general performance cost." },
  { stem: "Read: 'A grant will fund the first year of the project, but the team must demonstrate measurable outcomes before renewal.' What condition applies?", correct: "Further funding depends on results.", distractors: ["The first year has no funding.", "The project cannot collect measurements.", "Renewal is guaranteed in advance."], topic: "Reading for detail", explanation: "The phrase before renewal establishes a results-based condition for future funding." },
  { stem: "Read: 'The review praises the book's accessible examples but criticises its lack of engagement with opposing theories.' Which summary is most accurate?", correct: "It is clear but not sufficiently balanced.", distractors: ["It is inaccessible and theoretically comprehensive.", "It contains no examples or criticism.", "It is praised without qualification."], topic: "Reading for synthesis", explanation: "The review combines a positive comment on clarity with a criticism of limited balance." },
  { stem: "Read: 'Despite the forecast of heavy rain, the match went ahead because the drainage system had recently been upgraded.' What allowed the match to proceed?", correct: "Improved drainage.", distractors: ["A change in the forecast.", "The cancellation of the match.", "The absence of any rain forecast."], topic: "Reading for detail", explanation: "Because introduces the direct reason the match could proceed." },
  { stem: "Read: 'The company claims the packaging is recyclable. The report adds that local facilities accept only part of the material.' What qualification is implied?", correct: "Recyclability depends on local facilities.", distractors: ["The packaging cannot be produced.", "Every facility accepts all materials.", "The company makes no environmental claim."], topic: "Reading for precise meaning", explanation: "The report limits the broad claim by adding a condition about local processing capacity." },
  { stem: "Read: 'Rather than replacing face-to-face teaching, the platform was introduced to give students additional practice between lessons.' What is its intended role?", correct: "A supplement to classroom teaching.", distractors: ["A complete replacement for teachers.", "A tool used only during examinations.", "A platform for removing practice."], topic: "Reading for main ideas", explanation: "Rather than replacing explicitly contrasts the platform with replacement and identifies a supplementary role." },
  { stem: "Read: 'The first estimate assumed stable fuel prices. After prices rose sharply, the projected savings disappeared.' Why did the estimate change?", correct: "Its original assumption no longer held.", distractors: ["The project used less fuel than expected.", "Fuel prices remained stable.", "Savings were never included in the estimate."], topic: "Reading for cause and effect", explanation: "The rise in fuel prices invalidated the condition on which the estimate depended." },
  { stem: "Read: 'The article distinguishes between access to information and the ability to evaluate it. It argues that the latter is increasingly important online.' What distinction is made?", correct: "Finding information is different from judging its quality.", distractors: ["Online information is always accurate.", "Evaluation makes access impossible.", "Information and judgement are identical."], topic: "Reading for precise meaning", explanation: "The passage explicitly contrasts obtaining information with evaluating reliability." },
  { stem: "Read: 'The neighbourhood garden began as a food-growing project, but meetings gradually became its most valued feature.' What unexpected development occurred?", correct: "The social function became more important than the original one.", distractors: ["Food growing was banned immediately.", "Meetings were never held.", "The garden became a private office."], topic: "Reading for inference", explanation: "The contrast between began as and gradually shows a shift toward community interaction." },
  { stem: "Read: 'The reviewer accepts the figures but questions whether the sample represents rural households.' What concern is raised?", correct: "The findings may not generalise to all groups.", distractors: ["The figures were calculated incorrectly.", "Rural households were overpaid.", "The sample included no measurements."], topic: "Reading for writer attitude", explanation: "Questioning representativeness concerns whether results can be applied beyond the sampled group." },
  { stem: "Read: 'The museum's digital archive is free to browse, while high-resolution downloads require registration.' Which statement is true?", correct: "Viewing is open, but downloads have an extra requirement.", distractors: ["All content requires payment.", "Downloads are impossible.", "Registration is needed only to enter the museum."], topic: "Reading for detail", explanation: "While contrasts the unrestricted browsing option with the registration requirement for downloads." },
  { stem: "Read: 'The manager's email was brief, but the repeated use of “we” and “together” made the message sound reassuring.' What created the tone?", correct: "Inclusive language.", distractors: ["Technical vocabulary.", "A threatening command.", "A lack of any audience reference."], topic: "Reading for writer attitude", explanation: "We and together include the audience and create a sense of shared responsibility." },
  { stem: "Read: 'The experiment produced a result contrary to the initial hypothesis. The researchers describe this as useful because it reveals a limitation in the current model.' How do they view the result?", correct: "As evidence that can improve the model.", distractors: ["As proof that experiments are useless.", "As confirmation of the original hypothesis.", "As a result that should be hidden."], topic: "Reading for inference", explanation: "The researchers treat an unexpected result as information about model limitations." },
  { stem: "Read: 'Applications submitted after the deadline will be considered only if places remain.' What does this mean?", correct: "Late applications are possible but not guaranteed consideration.", distractors: ["Late applications always receive priority.", "The deadline has been removed.", "No application can ever be submitted."], topic: "Reading for detail", explanation: "Only if places remain makes consideration conditional rather than guaranteed." },
  { stem: "Read: 'The author begins with a personal story, then moves to survey data and ends by acknowledging a limitation.' What is the likely purpose of this structure?", correct: "To engage readers, support the point, and remain cautious.", distractors: ["To avoid presenting any evidence.", "To replace the conclusion with an advertisement.", "To make the argument entirely fictional."], topic: "Reading for text organisation", explanation: "The sequence combines engagement, evidence and a qualification of the claim." },
  { stem: "Read: 'Although the device is more expensive initially, its lower maintenance requirements make it cheaper over five years.' What comparison is being made?", correct: "Higher upfront cost versus lower long-term cost.", distractors: ["A cheap device with high reliability.", "Two devices with identical costs.", "Maintenance that becomes more expensive over time."], topic: "Reading for comparison", explanation: "Although marks the contrast between initial price and total cost over time." },
];

const functional: Seed[] = [
  { stem: "Your colleague proposes a plan you partly support but think needs more detail. What is the most appropriate response?", correct: "The overall idea is promising, but could we clarify the implementation steps?", distractors: ["This is obviously perfect; change nothing.", "I refuse to discuss any plan.", "You must accept my completely different idea."], topic: "Functional language and interaction", explanation: "The response acknowledges the idea while diplomatically requesting clarification." },
  { stem: "You need to interrupt a formal presentation to ask for clarification. What should you say?", correct: "Sorry to interrupt, but could you clarify what you mean by the final point?", distractors: ["Stop. That makes no sense.", "Talk faster and explain it now.", "I will ignore the point entirely."], topic: "Functional language and interaction", explanation: "The phrasing is polite, direct and appropriate for a formal interaction." },
  { stem: "A service has not replied to your previous email. Which follow-up opening is most suitable?", correct: "I am writing to follow up on my email of 12 May regarding the application.", distractors: ["Why have you ignored me again?", "Answer immediately or else.", "You probably lost my email, didn't you?"], topic: "Functional language and interaction", explanation: "The opening identifies the previous message and topic without making an unsupported accusation." },
  { stem: "You disagree with a proposal in a meeting but want to keep the discussion constructive. What should you say?", correct: "I see the advantage, although I am concerned about the effect on smaller teams.", distractors: ["That is a ridiculous suggestion.", "No one could possibly agree with you.", "I have nothing useful to add."], topic: "Functional language and interaction", explanation: "This hedged disagreement recognises a benefit and gives a specific reason for concern." },
  { stem: "You want a friend to recommend a reliable course. Which question is natural and specific?", correct: "Would you happen to know of a course that focuses on academic writing?", distractors: ["Tell me every course you know.", "You know a course, yes?", "Which course is the only course?"], topic: "Functional language and interaction", explanation: "Would you happen to know is a polite request and the relative clause specifies the need." },
  { stem: "You must decline an invitation because of a prior commitment. What is the best reply?", correct: "Thanks very much for inviting me, but unfortunately I already have an arrangement that evening.", distractors: ["No. Do not ask me again.", "I cannot attend because invitations are inconvenient.", "Maybe, although I know I will not go."], topic: "Functional language and interaction", explanation: "The reply expresses appreciation, gives a brief reason and declines clearly." },
  { stem: "A customer asks when a delayed order will arrive, but you cannot promise a date. What should you say?", correct: "I cannot confirm a delivery date yet, but I will update you as soon as I have one.", distractors: ["It will definitely arrive tomorrow.", "There is no point asking us.", "Your order is not our responsibility."], topic: "Functional language and interaction", explanation: "The response is honest about uncertainty and offers a concrete next action." },
  { stem: "You want to make a suggestion at the end of a discussion. Which phrase fits a professional setting?", correct: "Perhaps we could trial the approach with a smaller group first.", distractors: ["Just do what I said.", "There is only one possible answer.", "You should have thought of this earlier."], topic: "Functional language and interaction", explanation: "Perhaps we could is a measured suggestion, and a smaller trial reduces risk." },
  { stem: "You are writing a review and want to introduce a limitation. Which linking phrase is appropriate?", correct: "That said, the study is based on a relatively small sample.", distractors: ["For no reason, the study is perfect.", "As a result of nothing, the sample is large.", "In contrast to agreeing, there is no limitation."], topic: "Functional language and interaction", explanation: "That said introduces a contrasting qualification after a preceding point." },
  { stem: "A colleague has helped you meet a deadline. What is a suitable professional thank-you?", correct: "I really appreciate your help; we would not have met the deadline without it.", distractors: ["You did what you were supposed to do.", "The deadline was unimportant anyway.", "I expected you to solve everything."], topic: "Functional language and interaction", explanation: "The response clearly expresses gratitude and links the help to a concrete result." },
  { stem: "You need to ask a speaker to repeat one detail. Which request is most polite?", correct: "Could you possibly go over the figures for the second quarter again?", distractors: ["Repeat that.", "I was not listening, start over.", "The figures are impossible to hear."], topic: "Functional language and interaction", explanation: "Could you possibly and the specific request make the interruption courteous and efficient." },
  { stem: "You want to soften a claim in an academic paragraph because the evidence is limited. Which wording is best?", correct: "These findings appear to suggest that the approach may be beneficial.", distractors: ["These findings prove the approach always works.", "Nobody can question this result.", "The approach is certainly perfect."], topic: "Functional language and interaction", explanation: "Appear to suggest and may be beneficial appropriately signal limited certainty." },
  { stem: "Your team has two possible dates and needs a decision. How can you move the discussion forward?", correct: "Could we agree on a preferred date today and keep the other as a backup?", distractors: ["Choose now or the project is over.", "Dates do not matter at all.", "I will decide without consulting anyone."], topic: "Functional language and interaction", explanation: "The proposal offers a practical decision rule while leaving a contingency." },
  { stem: "You are introducing evidence from another source in a report. Which sentence is appropriate?", correct: "Recent survey evidence supports this interpretation, particularly among younger respondents.", distractors: ["Somebody somewhere says this is true.", "Everyone agrees, so evidence is unnecessary.", "The source is irrelevant but I will cite it."], topic: "Functional language and interaction", explanation: "The sentence identifies the evidence and gives its relevant scope without overgeneralising." },
  { stem: "A visitor asks for directions, and you are unsure. What is the most helpful response?", correct: "I am not completely sure, but the information desk should be able to point you in the right direction.", distractors: ["Go anywhere; it is probably nearby.", "I have no idea, ask someone else.", "The building has no directions."], topic: "Functional language and interaction", explanation: "The response is transparent about uncertainty and directs the visitor to a reliable source." },
  { stem: "You want to emphasise that a deadline is flexible but still important. What should you write?", correct: "While the date is negotiable, we would appreciate receiving the draft by Friday if possible.", distractors: ["The date is both fixed and irrelevant.", "Send it whenever you feel like it.", "The deadline cannot be discussed under any circumstances."], topic: "Functional language and interaction", explanation: "While introduces a balanced contrast between flexibility and a preferred target." },
  { stem: "You are responding to a complaint and need to acknowledge the problem before explaining the solution. Which opening is best?", correct: "I understand why this has been frustrating, and I am sorry for the inconvenience caused.", distractors: ["The problem is entirely your fault.", "There is no reason to complain.", "You should have read everything more carefully."], topic: "Functional language and interaction", explanation: "The opening recognises the customer's experience and apologises without escalating the situation." },
  { stem: "You want to check that everyone has the same understanding of a decision. Which phrase is suitable?", correct: "Just to make sure we are on the same page, are we postponing the launch until June?", distractors: ["You all understood me, obviously.", "I assume nobody has questions.", "The decision is secret, so do not repeat it."], topic: "Functional language and interaction", explanation: "The phrase checks shared understanding and restates the decision as a clear question." },
  { stem: "You need to explain that one factor is important but not the only one. Which wording is accurate?", correct: "Cost is a significant consideration, but it is not the sole basis for the decision.", distractors: ["Cost is the only thing that matters.", "Cost has no relevance whatsoever.", "The decision cannot involve any considerations."], topic: "Functional language and interaction", explanation: "Significant but not sole communicates relative importance precisely." },
  { stem: "You are asking a lecturer whether a source is acceptable for an assignment. Which email sentence is most appropriate?", correct: "Could you let me know whether this source would be suitable for the assignment?", distractors: ["Is this source okay or not?", "You need to approve this immediately.", "I will use it, so there is no need to reply."], topic: "Functional language and interaction", explanation: "Could you let me know whether is a polite and grammatically complete academic request." },
  { stem: "You want to transition from a problem to a possible solution in a presentation. Which phrase works best?", correct: "With this challenge in mind, the next section considers two possible responses.", distractors: ["Forget the challenge and move on randomly.", "There is no response worth considering.", "The next section repeats the problem without purpose."], topic: "Functional language and interaction", explanation: "With this challenge in mind creates a logical link between the problem and proposed responses." },
  { stem: "You need to tell a colleague that a task is incomplete without sounding accusatory. What should you say?", correct: "The draft is a useful start; could you add the supporting figures before we circulate it?", distractors: ["The draft is careless and unusable.", "You clearly did not try.", "I will replace the whole thing without explanation."], topic: "Functional language and interaction", explanation: "The response recognises progress and states the specific improvement needed." },
  { stem: "You are concluding an argument while acknowledging an alternative view. Which sentence is strongest?", correct: "Although the alternative has some merit, the available evidence favours the proposed approach.", distractors: ["Anyone who disagrees is wrong.", "Evidence is irrelevant to this conclusion.", "There are no alternative views."], topic: "Functional language and interaction", explanation: "Although acknowledges a counterargument before giving a reasoned conclusion." },
  { stem: "You want to invite further questions at the end of a formal talk. Which closing is suitable?", correct: "Thank you for listening. I would be happy to take any questions.", distractors: ["That is all; do not ask anything.", "You should already know the answers.", "Questions would only waste time."], topic: "Functional language and interaction", explanation: "The closing is conventional, polite and clearly opens the floor for questions." },
    { stem: "You need to correct a small factual error in a shared document. What is the most tactful note?", correct: "I think the date in paragraph three may need checking; the source lists it as 2019.", distractors: ["The date is wrong, as usual.", "You have misunderstood the entire document.", "I changed it without telling anyone."], topic: "Functional language and interaction", explanation: "I think and may need checking soften the correction while providing verifiable evidence." },
  { stem: "A meeting has become unfocused. Which phrase best brings the group back to the agreed objective?", correct: "Could we return to the main question and decide which option best meets the project's objective?", distractors: ["This discussion is pointless, so stop talking.", "Choose whichever option you prefer without checking the aim.", "The original objective no longer matters."], topic: "Functional language and interaction", explanation: "The response politely redirects the discussion and links the decision to a shared objective." },
];
export const ENGLISH_B2_QUESTIONS: Question[] = [
  ...makeQuestions("VOC", vocabulary, "基礎"),
  ...makeQuestions("GRAM", grammar, "進階"),
  ...makeQuestions("READ", reading, "情境"),
  ...makeQuestions("FUNC", functional, "情境"),
];
